version: "3.9"

services:
  backend:
    build: ./backend
    container_name: nestjs_app
    ports:
      - "3001:3000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursos_alunos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
